node {


        stage('Checkout') {

            git url: 'https://github.com/BenSalem-ChamsEddine/PFE.git', credentialsId:  'git-credit-ID', branch: 'master'

        }

        stage('Build') {
	  dir ('Eureka-Service') {

            sh 'mvn clean package'

            def pom = readMavenPom file:'pom.xml'

            print pom.version

            env.version = pom.version
	  }
        }

        stage('Image') {

            dir ('Eureka-Service') {

	      docker.build "pfe_eurekaservice"
	
            }

        }

        stage ('Final') {

            build job: 'Gestion-CV-Service-Pipeline', wait: false

        }      

}
