#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=chams1991
#
#spring.datasource.dbcp2.test-while-idle=true
#spring.datasource.dbcp2.validation-query=SELECT 1
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: chams1991
        dbcp2:
            test-while-idle: true
            validation-query: SELECT 1

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect