#server.port=8081
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/gestioncv
#
#management.security.enabled=false

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://172.16.39.46:5432/gestioncv

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:8761
