#server.port=8081
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/gestioncv
#
#management.security.enabled=false

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/gestioncv

management:
  security:
    enabled: false
