#server.port=8081
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/gestioncv
#
#management.security.enabled=false

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.100:5432/gestioncv

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
