server:
    port: 8082

security:
    user:
        name: admin
        password: 123

management:
  security:
    enabled: false

spring:
    datasource:
        url: jdbc:postgresql://192.168.1.100:5432/mycyn
    http:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
            resolve-lazily: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: bensalemchams@gmail.com
        password: chams1991
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
