node {


        stage('Checkout') {

            git url: 'https://github.com/BenSalem-ChamsEddine/PFE.git', credentialsId:  'git-credit-ID', branch: 'master'

        }

        stage('Build') {
	  dir ('Config-Service') {

            sh 'mvn clean package'

            def pom = readMavenPom file:'pom.xml'

            print pom.version

            env.version = pom.version
	  }
        }

        stage('Image') {

            dir ('Config-Service') {

	      docker.build "pfe_configservice"
	
            }

        }

        stage ('Run') {

            docker.image("pfe_configservice").run('-p 8888:8888 --expose=8888 -t pfe_configservice:latest')

        }

        stage ('Final') {

            build job: 'Eureka-Service-Pipeline', wait: false

        }      

}
