node {
	def app

        stage('Checkout') {

            git url: 'https://github.com/BenSalem-ChamsEddine/PFE.git', credentialsId:  'git-credit-ID', branch: 'master'

        }

        stage('Build') {
	  dir ('Gestion-Entretien-Service') {

            sh 'mvn clean package'

            def pom = readMavenPom file:'pom.xml'

            print pom.version

            env.version = pom.version
	  }
        }

        stage('Image') {

            dir ('Gestion-Entretien-Service') {

	      app = docker.build "bensalemchamseddine/pfe/pfe_gestionentretienservice"
	
            }

        }

	stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://hub.docker.com/r/bensalemchamseddine/pfe/', 'dockerHub-credit-ID') {
	    echo 'authentification successfull'
            app.push("pfe_gestionentretienservice")
            app.push("latest")
        }
    }

        stage ('Run') {

            docker.image("pfe_gestionentretienservice").run('-p 8082:8082 --expose=8082 -t pfe_gestionentretienservice:latest')

        }     

}
